//app
export const LOADING = 'LOADING';
export const LOADING_END = 'LOADING_END';
//app - guest
export const GUEST_FORM_CHANGE_VALUE = 'GUEST_FORM_CHANGE_VALUE';
export const GUEST_FORM_RESET = 'GUEST_FORM_RESET';
export const GUEST_SIGN_UP = 'GUEST_SIGN_UP';
export const GUEST_SIGN_UP_FAIL = 'GUEST_SIGN_UP_FAIL';
export const GUEST_SIGN_UP_SUCCESS = 'GUEST_SIGN_UP_SUCCESS';

//user
export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_IN_FAIL = 'USER_LOGGED_IN_FAIL';
export const USER_LOGGED_IN_SUCCESS = 'USER_LOGGED_IN_SUCCESS';

export const USER_REFRESH = 'USER_REFRESH';
export const USER_REFRESH_FAIL = 'USER_REFRESH_FAIL';
export const USER_REFRESH_SUCCESS = 'USER_REFRESH_SUCCESS';

export const USER_FORM_CHANGE_VALUE = 'USER_FORM_CHANGE_VALUE';
export const USER_UPDATE = 'USER_UPDATE';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';

export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';

export const USER_REFRESH_TOKEN = 'USER_REFRESH_TOKEN';

//gym
export const GYM_FETCH = 'GYM_FETCH';

//course
export const COURSE_FETCH = 'COURSE_FETCH';

//favorite gym
export const FAVORITE_GYM_FETCH = 'FAVORITE_GYM_FETCH';
export const FAVORITE_GYM_ADD_NEW = 'FAVORITE_GYM_ADD_NEW';
export const FAVORITE_GYM_REMOVE = 'FAVORITE_GYM_REMOVE';

